### ISSUE TITLE
Cannot create a new transaction

### ISSUE THREAD

**Issue by ulrichard** [quorumwallet/contracts#1]
This is more an issue with the hosted version at https://quorumwallet.com than with the contracts in this repo. But I didn't find a better place to report.
In the past, quorumwallet worked nicely, but now I can't create a new transaction. I always get the following errors:
Error: read tcp 147.75.197.5:8545->147.75.197.5:38678: i/o timeout
Error: read tcp 147.75.197.5:8545->147.75.197.5:38734: i/o timeout
This is with the Quorum RPC node. If I choose Etherscan, I can't even load my wallet.

**Comment by ulrichard** [comment]
Since the website no longer works, could you explain how I can transfer my funds from mist or the commandline?
I can see the funds when I watch the generated wallet contract in the Ethereum Wallet GUI, and I can call "CreateTransfer" and the see it as pending ref. But I don't know how to sign and execute it afterwards.

**Comment by axic** [comment]
@ulrichard I'm sorry I've missed your message. Let me look into the issue.

Are you seeing this issue only with signing a transaction?

## 

Here are utilities to generate signatures: github.com/axic/ethereum-bsm

The transfer reference is taken as a hex string and signed as a Bitcoin message. The reference and the signature components have to be sent to `signBitcoin` (see https://github.com/quorumwallet/contracts/blob/master/wallet.sol#L65).

**Comment by axic** [comment]
Also which network are you working with? ETH or ETC?

**Comment by ulrichard** [comment]
Thanks for the link to ethereum-bsm. I will look into it.

At first I had the issue only with signing, but now I can't even load my wallet. Now I press the "let's go already" button, and nothing happens.

The ETH were deposited to quorum before the fork, so as long as I send them to kraken, it should not matter wether it runs on ETH or ETC.

**Comment by ulrichard** [comment]
I didn't get the parameters in a format suitable for the contract. 
The mail I tried to send you with the details was bounced by the gmail spam filter. 
So I post it here:

-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

hQIOAyNb+bRMpM5qEAf+LjP2Gt/daO89KtsAHB8/+L6Tc2QNO4k37EfvQyA9nSt4
hYPWUtzPEPltY/2Gl2abGSShjGuXPlHAkZCQKQVktu3BgybhCta96d6sAAPvByTk
XXSJUra/0oswM4z1LrjDiBVpi6pgwOD6D1EcrLhqETY53rkrEeBsWPm0pvn+dXJe
G+SCmOofpBU9xMKEIlASQBPX+C5kmvr4EROOGTWCkRK1ScN2fqUFlNTGYENJtkrf
rqJhTdZ/cqZFBmM8NV54rsuM8L/MLaWaCpj5/igrNPYayaFLmnqmH4kf1WOhfJi3
LPJAw1o/EgpWl83ps1vCKo0/d0NYZFzogzrJAOVNUAgA0yIDeoLSgFT2Y/WdiIGZ
Q+lIQS9710ziEogRDztMI9HMBkkyW3ObpWpql/d+T9IRGWVyW9jKFd9j4AR/Vwtm
EIeH0aXc5W23WKcER8q8olc5NSEoQYB56nfSzeRgUi2CxDLtee53ztOUQc+0ZPJM
unoWlxXtE/jsYX57uMjvY2fhny0X/Y1slGrHy9QMeJ9fySbCBnua6/I36/avaYcT
jee82jhCUUBhwck1CsK8mUVs9os6XIKsnZEeMcGRAXQYGjZ4qomBvUZfzzSavMWa
mfpBmU9VKTLs+qbyOOZlWEKVJ0NkfWtNqGxQumIONQaHw7dxfUlTNN9aW9OXKQCg
/YUBDAMAAAAAAAAAAAEH+gJVRPzoth/7RTRk1NtbrZ75ipE8ABqx6FaAJOE4Yv11
OFdPloCktCGNVoO1NMOcZNONxaduIyP6zIHgjWAhRwGXlz+w0lB0BT4n5x2zPk5r
E5rQC0YBOts40+JB+frUimDKZy4kdJUNJ2Z4OvuAjASNCUAxrz0Xg6i92IBqHhNT
1NUC2DxY3SO1dkt1+Q59PKBHSiC2/kggx5gy7a56qim28afIFuUbTbt9ymCY1rSj
c4Uu9js2RlSwNdpw0Kw5lnIIQxE9dHAYXW8f55A/54fkfjYAgg5P+4WDK+vyt2WW
0b3gadu2/T8fSK3OsHaj6tE+aSWOpY4qAGZtsndW717S6gEqAybycWz4EHH6nWTX
SWCiKpM0hQwRNpp3iXo/p5SgBsVZ4VFrM5Nm0k9Zh0C6Jr428xu1ou+ootVLC9jG
CbhrCoXLOqhcy+Xj4pk4VHP+y5LQU9kHKqGpvwEXt1yshSFw/8R2XYv5rl3AhteD
HFggb8Ckbw0YPez+E6RiCQ4SS93StBxvOX5lEtauYjAaTCXVfQ4tc09wVAkYHJlz
V9RdoboQMJD0YeowRA7dthXkRcu59zR70soJiHhLzzvs21EFEs+lwAFzl6KYJH9S
gIheNIGnciuMY5eCTMHh9T2vY6537t/AfV9dCEmBjp/9fUgWJVTwkXKEM/NBC7Xd
5NqF5EtJNJeMjlZbOOXWShrWHgqUlAEPcUI7tGugi18lb9IqY5LrKMpRxLOxpnq+
nBj3LbWgAK8SRqWdehFSURO0iUcDO3AmPG7t7r+/N6/Pysv8zi95iLroqrx33/R8
RlMN5c8w83xEDOsIe5CVuv7bNfUBUFzLbR810gHhL+QKWQhE2x83jxG8FUE3Xp/p
KInqfHAGKo+ZIRQfdVmWHmbB0OOes+sG0GgHQ4WnwU0HTeSmw221j6Vz8X1KVhCt
CrBmiZjcnz3dQuGvf99AXCjN+vln+3TGB/VWhq3slnXta622gkQiAH0wYEGf1cIL
Wsqfa6WsLk89SkDbvxJ32QHPUrjbE984s4hbRvFXhpGJP6sCMgBh/7p0pJJwhm3m
NBXujNdE3O14LQY86rcADmvD1KT3JApU6GtrnkuAyaZ4+eysSIL+Gqqm//xUi3Tn
fLWbRX8SY8atcFFVkKkv+cVy951ZmRYmTFgnuc4yrKk1TglPxQBJtVnFnvvnCXgZ
WfFzqGTu4+ovEDQEQxrw5SeBZSqHhLXEUX+g0axMVdDFiYwyNN+yMjdO5ocpL4HE
jcoSw5fq9Ms4fEJpVa/fscUVtBPn4fGh6VPtRTgy0Wo3A2FrcZlPbxEJgokliunG
yzZHV/u47VFxhJjZvKKTCedBbLzl8Xe3ITc8le6GoQtb+JTpJBY9thjW/oK/rLMD
B2NYbGdrnRuHYPNnh89fp6bV4zY3y8xxQfaq/5o1r8DeKPnxIieYGJxqv0HG1UUx
wlaBlyHfLsFBG0LNpC6eDZOKxAzPfZXHW4vJuAABSBxtiVpXez0NPdqYuvjvJ7On
EOQwiv4KBwPuloCMD+J+5fBpFEMi/X7tMGoJ+GbS+UuNdN5H/lVZQ3lmcRGHj25Q
HHy9fnLIC8GtXm0DqGjXaDcHCgLdOXdZPmye98mHqrKgnnnGPaR16Opgx84Kt0Vz
LcS7qezOOfoXC45nQOWtfpwlXCm7tARbpiJblV0Zp7Im3oZ2yITJT/h5EsEtvbVi
Lc/piqqm4gPBD9wE8hpRQfblgUSRhKrJ3roRsPzRcQKMjC4cMjNQ3fJfccPMUiPN
Zd0oyPCEoGdGzc81XXkdrTQc3FWS4GgFi3SbfsnZXjZbqPjPeS9Eb8AldW09didr
KZp0gzhmxW8OVBQ8LDTOG5LHQ5D3QYF6PF+fDBXwzGbLOFrWQ3AyYXncE8Wx1NwP
bdM+ZEyiLxPeY9qWp/MrtjZnGd2sfnjjd0++Q8nB8sc8E9NyvUlbRh7v/WzSnDCX
qrt6LSgEr4aAHCdos/JFz6HtiwTpnGL78zlyzOk2JUHXBcvsTqVHpmjrNBZB53oH
zbTQj3GirGir56se85eTCOgKh3AQplJ+r2a7OyO0HeNqV3choNosdGv3GRWsjkWh
xdPWKSk+7jraZFppZa21fODD5XW9zjpJDoBUpqzyUsn29PKEMZ8ZnqG/f81LeuSG
JrrM9X6vb2lzn4men2oxqVyBVDtRxua6W09YzJF5yE8adPLlze8CkWeOdmafLl5R
gRePANlsczRwxbcku+8UMyifPd1xi/gxuZrtt9iAReviRA/Vt/m0ImIUGeMqJoT9
oTmMwcktWtvzXZqMQgSJI2CBzYEsHsVt7425ops+l2oxJmzc/w/1jgjuxORt0wC7
WOA5afcQa67ixX39McA0mA1vV6At82WC/KErReMGCXZEcWORQMfXwBTvODfr/UzJ
6Svog090Ni5UJm4pgA5F+VGIXyUbscFsoA+bhBum2UaDjJuQUFz0Wq5YJGeFQ+nz
QUoC5VYEIsA0rXmRWfexhSvZ1b0aHDneizBtz0b19z79bs8D16INUYqqnGbyc56o
p+bucbRc2HxI5zNx63dtLFvS/hDyaYpdzGx4lrr6tUjppi8DWQ==
=vv7L
-----END PGP MESSAGE-----

**Comment by axic** [comment]
@ulrichard Can you please DM me on gitter.im tomorrow?
